
import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { Star, MessageSquare, CheckCircle2, ChevronRight, AlertTriangle, ShieldAlert, CreditCard } from 'lucide-react';
import { api } from '../services/api';

const CustomerView: React.FC = () => {
  const { businessId } = useParams<{ businessId: string }>();
  const [business, setBusiness] = useState<any>(null);
  const [rating, setRating] = useState<number | null>(null);
  const [hoverRating, setHoverRating] = useState<number | null>(null);
  const [feedback, setFeedback] = useState('');
  const [name, setName] = useState('');
  const [mobile, setMobile] = useState('');
  const [step, setStep] = useState<'rating' | 'feedback' | 'success'>('rating');

  useEffect(() => {
    async function loadBusiness() {
      if (businessId) {
        const biz = await api.getBusiness(businessId);
        setBusiness(biz);
        if (biz) {
          api.incrementScanCount(businessId);
        }
      }
    }
    loadBusiness();
  }, [businessId]);

  if (!business) return <div className="p-8 text-center">Loading...</div>;

  // Subscription Restriction Logic
  const now = Date.now();
  const msInDay = 24 * 60 * 60 * 1000;
  const gracePeriod = msInDay * 3;

  const isExpired = business.expiryDate < now;
  const isHardBlocked = business.status === 'DISABLED' || (business.expiryDate < (now - gracePeriod));
  const isSoftBlocked = !isHardBlocked && isExpired;

  // HARD BLOCK: Redirect / Page Overwrite
  if (isHardBlocked) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center p-6">
        <div className="w-full max-w-md bg-white rounded-[40px] shadow-2xl p-10 text-center border-t-[12px] border-rose-600 animate-in zoom-in-95 duration-500">
          <div className="bg-rose-100 p-6 rounded-full w-fit mx-auto mb-8">
            <ShieldAlert size={64} className="text-rose-600 animate-bounce" />
          </div>
          <h1 className="text-3xl font-black text-slate-900 mb-4 tracking-tight uppercase">Subscription Expired</h1>
          <p className="text-slate-500 font-bold leading-relaxed mb-8">
            "Kshama karein, is vyapar ka SmartReview subscription expire ho chuka hai. Feedback system temporary taur par band kar diya gaya hai."
          </p>
          <div className="p-4 bg-slate-50 rounded-2xl border border-slate-100">
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Business Information</p>
            <p className="text-sm font-bold text-slate-800 uppercase">{business.name}</p>
          </div>
        </div>
      </div>
    );
  }

  // SOFT BLOCK: Temporarily Disabled
  if (isSoftBlocked) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center p-6">
        <div className="w-full max-w-md bg-white rounded-[40px] shadow-xl p-10 text-center border-t-[12px] border-amber-500 animate-in fade-in duration-500">
          <div className="bg-amber-100 p-6 rounded-full w-fit mx-auto mb-8">
            <AlertTriangle size={64} className="text-amber-600" />
          </div>
          <h1 className="text-2xl font-black text-slate-900 mb-4 uppercase tracking-tight">System Maintenance</h1>
          <p className="text-slate-500 font-bold leading-relaxed">
            "Dhanyavad humein visit karne ke liye. Yeh feedback portal abhi maintenance mein hai aur jald hi wapas aayega."
          </p>
          <div className="mt-8 pt-8 border-t border-slate-100 flex items-center justify-center space-x-2 text-slate-300">
            <CreditCard size={16} />
            <span className="text-[10px] font-black uppercase tracking-widest">Awaiting System Sync</span>
          </div>
        </div>
      </div>
    );
  }

  const handleRating = (r: number) => {
    setRating(r);
    // Directly go to feedback or success, but if high rating, we redirect BUT still want to save feedback possibly?
    // Old logic: > 4 stars -> redirect to Google Maps
    // We should probably save the rating first in background? 
    // For now keeping same flow: if >= 4 stars, we might not save a 'feedback' record unless they comment?
    // Actually, usually high rating means we WANT to record it.
    // Let's create a partial feedback record if we redirect?
    // For simplicity, sticking to existing UX: 
    // IF rating high -> Redirect. 
    // The user might not perform "Submit". 
    // To capture this data, we should probably submit immediately.

    if (r >= 4) {
      // Auto-submit high rating without comment
      const newFeedback: any = {
        // ID generated by DB or us
        businessId: business.id,
        rating: r,
        comment: '',
        customerName: 'Guest',
        customerMobile: '',
        timestamp: Date.now(),
        resolved: true // Positive feedback considered resolved or no action needed
      };

      api.addFeedback(newFeedback as any); // Fire and forget

      setTimeout(() => {
        window.open(business.googleMapsUrl, '_blank');
        setStep('success');
      }, 800);
    } else {
      setStep('feedback');
    }
  };

  const handleSubmitFeedback = async () => {
    if (business && rating) {
      const newFeedback = {
        // id: `fb-${Date.now()}`, // DB will gen ID or we can
        businessId: business.id,
        rating: rating,
        comment: feedback,
        customerName: name || 'Guest Customer',
        customerMobile: mobile || '',
        timestamp: Date.now(),
        resolved: false
      };
      await api.addFeedback(newFeedback as any);
    }
    setStep('success');
  };

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col items-center p-4 md:p-6 md:justify-center">
      <div className="w-full max-w-md bg-white rounded-3xl shadow-xl p-6 md:p-8 text-center animate-slide-up">
        <h1 className="text-xl md:text-2xl font-bold text-slate-800 mb-2">How was your visit?</h1>
        <p className="text-slate-500 mb-6 md:mb-8 font-medium">{business.name}</p>

        {step === 'rating' && (
          <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4">
            <div className="flex justify-center space-x-2">
              {[1, 2, 3, 4, 5].map((star) => (
                <button
                  key={star}
                  onMouseEnter={() => setHoverRating(star)}
                  onMouseLeave={() => setHoverRating(null)}
                  onClick={() => handleRating(star)}
                  className="transition-transform active:scale-90"
                >
                  <Star
                    size={48}
                    className={`transition-colors duration-200 ${(hoverRating || rating || 0) >= star
                      ? 'fill-yellow-400 text-yellow-400'
                      : 'text-slate-200'
                      }`}
                  />
                </button>
              ))}
            </div>
            <p className="text-sm text-slate-400 font-bold uppercase tracking-widest">Rate our service</p>
          </div>
        )}

        {step === 'feedback' && (
          <div className="space-y-6 animate-in fade-in slide-in-from-right-4">
            <div className="text-left space-y-4">
              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-2">
                  We're sorry! How can we make it better?
                </label>
                <textarea
                  value={feedback}
                  onChange={(e) => setFeedback(e.target.value)}
                  placeholder="Manager will read this privately..."
                  className="w-full h-32 p-4 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-500 outline-none resize-none transition-all"
                />
              </div>
              <div className="grid grid-cols-1 gap-4">
                <input
                  type="text"
                  placeholder="Your Name (Optional)"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="w-full p-4 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500"
                />
                <input
                  type="tel"
                  placeholder="Mobile Number (Optional)"
                  value={mobile}
                  onChange={(e) => setMobile(e.target.value)}
                  className="w-full p-4 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500"
                />
              </div>
            </div>
            <button
              onClick={handleSubmitFeedback}
              className="w-full bg-indigo-600 text-white font-bold py-4 rounded-xl flex items-center justify-center space-x-2 shadow-lg"
            >
              <span>Submit Message</span>
              <ChevronRight size={20} />
            </button>
          </div>
        )}

        {step === 'success' && (
          <div className="space-y-6 animate-in zoom-in-95 duration-300">
            <div className="bg-green-100 p-6 rounded-full w-fit mx-auto">
              <CheckCircle2 size={64} className="text-green-600" />
            </div>
            <h2 className="text-2xl font-black text-slate-900 tracking-tight">Dhanyavad!</h2>
            {business.settings.rewardType === 'COUPON' && rating !== null && (
              <div className="bg-indigo-50 border-4 border-dashed border-indigo-200 rounded-3xl p-6 mt-4">
                <p className="text-xs font-black text-indigo-600 uppercase tracking-widest mb-2">Your Reward</p>
                <p className="text-indigo-900 font-black text-2xl">{business.settings.couponCode || 'SAVE10'}</p>
              </div>
            )}
          </div>
        )}
      </div>
      <div className="mt-8 text-slate-400 flex items-center space-x-2 text-xs font-black uppercase tracking-widest">
        <MessageSquare size={14} />
        <span>Powered by SmartReview SaaS</span>
      </div>
    </div>
  );
};

export default CustomerView;
